import "./globals.css";
import Header from "../components/shared/Header";
import TopHeader from "../components/shared/TopHeader";
import Footer from "../components/shared/Footer";
import { SiteProvider } from "../context/SiteContext";

export const metadata = {
  title: "Almas",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="bg-white">
        <SiteProvider>
          <TopHeader />
          <Header />
          <div className="w-full h-80 bg-gray-100"></div>
          {children}
          <Footer/>
        </SiteProvider>
      </body>
    </html>
  );
}
