import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/shared/Header";
import TopHeader from "../components/shared/TopHeader";


export const metadata: Metadata = {
  title: "Almas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <TopHeader/>
        <Header/>
        <div className="w-full h-80 bg-gray-100"></div>
        {children}
      </body>
    </html>
  );
}
